services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    environment:
      - TS_AUTHKEY=
      - TS_HOSTNAME=Nottify
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: "host"
    restart: unless-stopped

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LASTFM_APIKEY: 
      ND_LASTFM_SECRET: 
      ND_SPOTIFY_ID: 
      ND_SPOTIFY_SECRET: 
    volumes:
      - "./data:/data"
      - "/path/to/music:/music"